language: python
python:
  - "2.7"

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs npm

install:
  - "pip install -r backend/requirements.txt"
  - "pip install -r backend/test-requirements.txt"
  - "cd frontend"
  - "npm install"
  - "npm run update-webdriver"
  - "cd .."

before_script:
  - psql -c 'create database parklabtest;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bin/dev_server &
  - sleep 3

script:
  - nosetests backend/tests --with-coverage --cover-package backend --cover-branches
  - frontend/node_modules/karma/bin/karma start frontend/test/karma.conf.js --single-run --browsers=Firefox
  - frontend/node_modules/.bin/protractor frontend/test/protractor-conf.js --browser=firefox

env: PYTHONPATH=backend/src:backend/tests DATABASE_URL=postgresql://postgres@localhost/parklabtest SECRET_KEY=snakes DEBUG=1 USER_ENABLE_EMAIL='' S3_BUCKET=bucket AWS_ACCESS_KEY_ID=key AWS_SECRET_ACCESS_KEY=secret

deploy:
  provider: heroku
  api_key:
    secure: DbEhMnV5Dh1KFt8hSDQi6oFsYHUhfiZ13AEGfyonm5aSPJs5FtdAf4ydVH05DBl18KQQ9UMyDLPzI/pPPX1KR6kkV/5Odfjqii35A/1DRnzDEgg4tqcZsWU5h9vQY/DNn/m04yiFohpxUVvthTZKkDIRfjIIVctPV7HQCTYckpA=
  app:
    master: parklab
  on:
    repo: freedomgames/Planet-Lab
after_deploy: ./bin/flush_db
